#!/bin/bash

# StaffAdmin - ngrok Setup Script
# This script provides instructions for setting up ngrok tunnels

echo "🌐 StaffAdmin ngrok Setup"
echo "=================================="
echo ""
echo "To expose your local services to colleagues, run these commands in separate terminals:"
echo ""
echo "Terminal 1 - Backend API:"
echo "  ngrok http 8000"
echo ""
echo "Terminal 2 - Optimizer API:"
echo "  ngrok http 9001"
echo ""
echo "Terminal 3 - Frontend:"
echo "  ngrok http 3000"
echo ""
echo "=================================="
echo ""
echo "After starting ngrok:"
echo "1. Copy the 'Forwarding' URLs from each ngrok terminal"
echo "2. Update CORS_ORIGINS in api/.env:"
echo "   CORS_ORIGINS=http://localhost:3000,<frontend-ngrok-url>"
echo ""
echo "3. Update NEXT_PUBLIC_API_URL in web/.env.local:"
echo "   NEXT_PUBLIC_API_URL=<backend-ngrok-url>"
echo ""
echo "4. Restart services: ./stop-all-services.sh && ./start-all-services.sh"
echo ""
echo "5. Share the frontend ngrok URL with your colleagues!"
echo ""
echo "=================================="
echo ""
echo "Example ngrok URLs will look like:"
echo "  https://abc123.ngrok.io"
echo ""
